---
- name: "fix /etc/hosts localhost ip"
  lineinfile:
    dest: '/etc/hosts'
    regexp: '127.*localhost*'
    line: '127.0.1.1   localhost localhost.localdomain localhost4 localhost4.localdomain4'
    state: present

- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item.replace('.', '-') }}$"
    line: "{{ hostvars[item].ansible_host }} {{ item.replace('.', '-') }}.{{ etc_hosts_domain }} {{ item.replace('.', '-') }}"
    state: present
  when: hostvars[item].ansible_host is defined
  become: yes
  with_items: "{{ groups['all'] }}"
  tags:
    - env_setup
